dependencies:
	pip install -r requirements.txt

pytest:
	pytest ./test_calculator.py

verbose:
	pytest -v ./test_calculator.py

everything:
	pytest -v

fast_mark:
	pytest -v -m fast

slow_mark:
	pytest -v -m slow
